### ISSUE TITLE
Fullscreen Shortcut (Ctrl+Command+F)?

### ISSUE THREAD

**Issue by lifyd** [screenisland/kanban-kit#14]
Can support for the fullscreen shortcut command: Ctrl+Command ()+F be implemented for the app? 

Just bought the app. Love it, but it would make my workflow more efficient if I could easy transition between fullscreen and normal window by using the shortcut (rather than using the trackpad and clicking the green icon). 

Thanks.

**Comment by gobijan** [comment]
Implemented with 1.0.3 :)
