### ISSUE TITLE
New Task keyboard shortcut should be `cmd-n`

### ISSUE THREAD

**Issue by mczepiel** [screenisland/kanban-kit#22]
"New whatever" is usually `command-n` within OS X apps; the shift-return (enter) doesn't match muscle memory

**Comment by WolfgangSteiner** [comment]
+1

**Comment by gobijan** [comment]
Nah CMD+N in OS X is usually a new window. That's the reason why I did not choose CMD+N

**Comment by mczepiel** [comment]
Well I'd argue that the shortcut is for whatever is commonly created as a new <thing>. i.e. Browsers/Find er chose Window as the default, but other apps use it for creating a new document/email/image/chat session/etc. 

Obviously your call but the behavior depends upon what makes sense for the app.

e.g. If you ever added a way  to create a new board I'd expect that to be `cmd-shift-n` as it is a less frequent operation versus the very common `cmd-n` for creating a new task in current board.

**Comment by gobijan** [comment]
Thank you for your input. I just had a look at apples calendar app and they use CMD+N to create a new task. So maybe this might be a good shortcut as CMD+N is unused anyway at the moment. 
I'll reopen this issue :)

**Comment by gobijan** [comment]
Update is in the App Store and processed by Apple now.
CMD + N is the new default for adding new tasks :)

**Comment by mczepiel** [comment]
Awesome, thank you very much for the reasoned investigation. Looking forward to the update.

**Comment by mczepiel** [comment]
Oh a quick note, make sure to update the user guide. http://screenisland.com/kanban-kit/guide/

EDIT: typo
