### ISSUE TITLE
"Create New Task" Should instead read "New Task" in the File menu

### ISSUE THREAD

**Issue by mczepiel** [screenisland/kanban-kit#23]
Typically there's no need to specify "Create" and the addition of the ellipsis indicates that there will be some followup dialog to interact with.

**Comment by mczepiel** [comment]
FWIW, I don't think the ellipsis is actually necessary in this case, but the "Create" is extraneous

**Comment by gobijan** [comment]
Fixed in 1.0.4. (incoming to MAS)
