### ISSUE TITLE
New Task keyboard shortcut incorrectly indicated as Shift+n in menu

### ISSUE THREAD

**Issue by mczepiel** [screenisland/kanban-kit#29]
Happy that cmd-n works as expected in the 1.0.4 update, but it's indicated incorrectly in the menu item.

![screen shot 2015-08-11 at 11 28 06 am](https://cloud.githubusercontent.com/assets/2964/9206389/57ccb114-401c-11e5-816d-bc353f3e1789.png)

**Comment by gobijan** [comment]
Stupid me. I forgot to clean the Build and somehow this artifact remained. Bug is fixed in my dev build now. If you find another bug let me know. If I won't hear from you within the next days I'll check in 1.0.5 with this fixed.

PS: Thx for your Feedback :)

**Comment by squill** [comment]
I just started using this app and I found that hitting Shif+n twice will open a new task.

**Comment by gobijan** [comment]
CMD+N is the new shortcut.
Fixed with 1.0.5 (pushed to App Store Review)-
