### ISSUE TITLE
[Feature] Colors Tasks

### ISSUE THREAD

**Issue by kneipp** [screenisland/kanban-kit#5]
It would be cool if possible set colors to each task.

Regards!

**Comment by guydavies** [comment]
I just bought Kanban Kit and this was one of the first things that I wished for :)  I notice that it's almost a year since the last comment, so I hope that there's potential for updates to the product I just bought ;)

**Comment by gobijan** [comment]
Hi @guydavies. I am currently finishing a big project and after that Kanban Kit will get some new features  ;)

**Comment by guydavies** [comment]
Awesome.  Thanks for the super quick response, and good luck with the big project :)
